FROM tukiyo3/centos8-build

WORKDIR /usr/local/src/

RUN yum install --nogpgcheck -y libnsl

ENV CXXFLAGS="-std=gnu++98"
RUN update-alternatives \
 --install /usr/bin/gcc gcc /usr/bin/gcc44 20 \
 --slave   /usr/bin/g++ g++ /usr/bin/g++44
ENV CC=/usr/bin/gcc44
ENV CXX=/usr/bin/g++44

#----------
# mysql-4.0
#----------
WORKDIR /usr/local/src/
COPY files/ .
RUN tar xzf mysql-4.0.30.tar.gz
WORKDIR /usr/local/src/mysql-4.0.30
# eucjpとsjisを有効化
RUN ./configure --prefix=/opt/mysql40 --with-charset=ujis --with-extra-charsets=sjis --quiet
RUN echo "/opt/mysql40/lib/mysql/" > /etc/ld.so.conf.d/opt-mysql40.conf
COPY etc/my.cnf.example-40 /etc/my.cnf.example-40
RUN make -s 1>/dev/null
#RUN make test
RUN make install

#-----
# link
#-----
RUN ln -s /opt/mysql40 /opt/mysql

#---------------
# php
#---------------
WORKDIR /usr/local/src/

#-----
# re2c
#-----
# phpの./configureでre2cのPATH指定方法がわからなかったため--prefixは指定していません
COPY files/re2c-0.16.tar.gz /usr/local/src/
RUN tar xzf re2c-0.16.tar.gz \
 && cd re2c-0.16 \
 && ./configure \
 && make -s \
 && make install

#-----
# lemon
#-----
COPY files/lemon.c /usr/local/src/
RUN gcc -o /usr/local/bin/lemon lemon.c

#-----
# flex
#-----
COPY files/flex-2.5.4a.tar.gz /usr/local/src/
RUN tar xzf flex-2.5.4a.tar.gz \
 && cd flex-2.5.4 \
 && ./configure --prefix=/opt/flex \
 && make -s \
 && make install

#------
# bison
#------
COPY files/bison-2.4.1.tar.bz2 /usr/local/src/
RUN tar jxf bison-2.4.1.tar.bz2 \
 && cd bison-2.4.1 \
 && ./configure \
 && make -s \
 && make install \
 && make install DESTDIR=/opt/bison

#---------------
# openssl 1.0.2
#---------------
WORKDIR /usr/local/src/
COPY files/openssl/openssl-1.0.2t.tar.gz /usr/local/src/
RUN tar xzf openssl-1.0.2t.tar.gz
WORKDIR /usr/local/src/openssl-1.0.2t
RUN ./config --prefix=/opt/openssl-1.0.2t shared
RUN make -s
RUN make install
RUN ln -s /opt/openssl-1.0.2t/lib /opt/openssl-1.0.2t/lib64

# php
WORKDIR /usr/local/src/
COPY files/php-5.2.17.tar.bz2 /usr/local/src/
RUN tar jxf php-5.2.17.tar.bz2

# configureを通すため。
RUN ln -s /opt/mysql/lib/mysql/libmysqlclient.so /opt/mysql/lib/mysql/libmysqlclient_r.so \
 && ln -s /opt/mysql/lib/mysql/libmysqlclient.a /opt/mysql/lib/mysql/libmysqlclient_r.a \
 && ln -s /opt/mysql/lib /opt/mysql/lib64

# patch
WORKDIR /usr/local/src/php-5.2.17
COPY ./files/php-patch/ /usr/local/src/php-patch/
RUN patch -p0 -b < ../php-patch/php-5.2.17.patch \
 && patch -p0 -b < ../php-patch/gmp.patch \
 && patch -p0 -b < ../php-patch/php_functions.patch
RUN yum install --nogpgcheck -y libnsl
RUN ./configure --quiet \
  --prefix=/opt/php52 \
  --with-apxs2=/usr/bin/apxs \
  --with-pear=/opt/pear52 \
  --disable-cgi \
  --enable-zend-multibyte \
  --enable-mbstring \
  \
  --with-mysql=shared,/opt/mysql \
  --with-pdo-mysql=shared,/opt/mysql \
  \
  --with-openssl=/opt/openssl-1.0.2t \
  --with-mhash=shared,/usr \
  --with-mcrypt=shared,/usr \
  --enable-sockets \
  --enable-pcntl \
  --enable-sigchild \
  --with-gd=shared \
  --with-jpeg-dir=/usr \
  --with-png-dir=/usr \
  --with-zlib \
  --with-zlib-dir=/usr \
  --with-ttf \
  --with-freetype-dir=/usr \
  --enable-gd-native-ttf \
  --enable-gd-jis-conv \
  \
  --with-config-file-path=/etc/ --with-config-file-scan-dir=/etc/php.d \
  \
  --with-libdir=lib64 \
  1>/dev/null

RUN make -s 1>/dev/null
RUN make test 1>/dev/null
# /etc/httpd/conf/httpd.confがhttpdパッケージとconfrictするため除外
RUN make install


RUN mkdir /data/
RUN cp -a /opt/php52/lib/php/extensions/no-debug-zts-20060613/gd.so /data/
WORKDIR /data/
